### ISSUE TITLE
Working demo

### ISSUE THREAD

**Issue by jomo666** [Bivee/eureca#1]
This is typical example why perl isn't popular for the web development. Probably this code is great. But after installing if (and resolving few dependencies (what could be automatised), started the app.

But after the [http://0:3000](http://0:3000) i got only one blank page with stupid heading and logo, without any links and so. So, checked `index.html.ep` and it really contains only this, so deleting the app, haven't time figuring out what controllers you implement and soo..

So, maybe the app itself is great and could be useful - it is presented in extremely wrong way. For getting more contributors, you should release at least an minimal working demo.

**Comment by dvinciguerra** [comment]
Sorry jomo, but this app is in a complete redesign process!

If you want to receive more news about it, please follow this repo and I can make a push to you see something of the new version.

**Comment by dvinciguerra** [comment]
Now we have a basic working demo @jomo666.
Thank you for your feedback! :)

**Comment by jomo666** [comment]
thank you, looks nice :).
